### ISSUE TITLE
Develop Python Best Practices Course

### ISSUE THREAD

**Issue by dadamsncsa** [nanoMFG/community#31]
## Description
Create a course mostly on how to structure a python app/library, but also some instruction on coding.  End up with a modern maintainable python app/library.

# Outline for python best practices

Step|App Prep Actions (done at end of previous step)|User Actions| Event | App Check Actions
-----|-----|-----|-----|-----
1| <ul><li>Protect main branch</li> <li>Create first issue</li><li>respond with first activity</li></ul>|open first pull request, commit LICENSE file | `pull_request.opened`|<ul><li>check if LICENSE exists at top-level</li></ul>
2|<ul><li>respond--ask user to commit .gitignore</li></ul> |user commits .gitignore|`pull_request.synchronize` | <ul><li>Check that it is the right file for Python?</li></ul>
3|<ul><li>respond: ask user to merge PR</li></ul>|Users merges PR| `pull_request.closed`| <ul><li>gate: Check if PR was actually merged </li></ul>
4|<ul><li>close first issue</li><li>create second issue</li><li>responds in closed PR with link to new issue for next</li><li>Introduce topic: Python packages and modules (issue body)</li></ul>|User commits __init__.py's and opens PR|`pull_request.opened`|<ul><li>gate: check for correct files/locations</li></ul>  |
5 |respond: Activity : Ask user to add a class and methods to outline the package |  User commits changes to branch| `pull_request.synchronize` | <ul><li>App checks for working skeleton code</li></ul> |  
6|<ul><li>App introduces docstring activity, includes example docstring for class and 1 function</li></ul> |User commits updates with docstrings for each method  | `pull_request.synchronize` |<ul><li>App checks doctrings</li><li>app generates documentation </li><li>app deploys docs on github pages</li><li>app responds with link to pages site</li><li>app approves pr</li></ul>| 
7 | <ul><li>respond: Ask user to merge PR</li></ul> | User merges PR | `pull_request.closed` | <ul><li>Check for merge</li><li>App replies with job well done and "checkpoint" summary of where the learning is at and where they are going</li></ul>
8 |<ul><li>app closes second issue</li><li>app opens 3rd issue</li><li>App provides link to next topic</li><li>Introduce Topic: Setup Tools and Testing</li><li>respond: Activity: Add `setup.py`</li></ul> | User commits setup.py (minimally to allow `pip install-e .`) and enable pytest | `pull_request.opened`|<ul><li>Check committed setup.py code</li></ul>
9 |<ul><li>respond with Activity: Write tests for methods</li></ul> | <ul><li>User creates local environment</li><li>user runs pytest</li><li>User adds tests for planned methods</li></ul> | `pull_request.synchronize`
10 | <ul><li>respond with activity: User adds working code to pass tests</li></ul> |<ul><li>User adds working module code</li><li>User runs tests until passing</li><li>user commits working code to branch</li></ul> | `pull_request.synchronize`
11| | |

## References
https://github.com/jazzband/pip-tools  
https://docs.python-guide.org/writing/structure/  
https://realpython.com/python-application-layouts/  
https://packaging.python.org/tutorials/packaging-projects/

**Comment by briancy02** [comment]
I think this is [another good link](https://data-flair.training/blogs/python-best-practices/) to be included in references

**Comment by briancy02** [comment]
I just realized another issue for this Epic would be to create the code for a complete template repo. We'll need to create all the files we expect the user to create in our course in some separate repo like 'python-best-practices-solution' so we can use that as a reference when making the user template repo.

**Comment by dadamsncsa** [comment]
Good idea, maybe make a solution branch in the template reop and leave it unmerged.

**Comment by briancy02** [comment]
[This ](https://machinelearningmastery.com/tutorial-first-neural-network-python-keras/)could be a good example project. They won't have to understand what every line means but it'll require users to create a data directory, learn to use pip/imports, and run tests on invalid datasets?

**Comment by dadamsncsa** [comment]
We discussed using image related ML model like MNIST recognition.  the question is how to incorporate as a simple module that fits the application structure from https://realpython.com/python-application-layouts/#application-with-internal-packages.  Maybe add module wit h"predict" and "train" methods. and a CLI app to run them.

**Comment by dadamsncsa** [comment]
Making issues for...
- [ ] Fix _init__.py step(s)
- [x] Fix the edit file links for init and model.
- [x] make gates consistent for steps 1-6
- [x] fix directory structure (solution)
- [x] Add tests for 4,5,6, add file check tests for 1-6
- [x] Add code to add test files at begining of pull request
- [ ]
